name: First Demo Action

on:
  push:
    branches:
      - master

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Start action
        run: echo "action started"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build, test, and deploy
        run: |
          echo "add other action to build"
          echo "test, and deploy your project"